/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/account/add/': RouteRecordInfo<'/account/add/', '/account/add', Record<never, never>, Record<never, never>>,
    '/account/add/microsoft': RouteRecordInfo<'/account/add/microsoft', '/account/add/microsoft', Record<never, never>, Record<never, never>>,
    '/account/add/offline': RouteRecordInfo<'/account/add/offline', '/account/add/offline', Record<never, never>, Record<never, never>>,
    '/account/list': RouteRecordInfo<'/account/list', '/account/list', Record<never, never>, Record<never, never>>,
    '/discover/': RouteRecordInfo<'/discover/', '/discover', Record<never, never>, Record<never, never>>,
    '/discover/game/': RouteRecordInfo<'/discover/game/', '/discover/game', Record<never, never>, Record<never, never>>,
    '/discover/game/install.[version]': RouteRecordInfo<'/discover/game/install.[version]', '/discover/game/install/:version', { version: ParamValue<true> }, { version: ParamValue<false> }>,
  }
}
