[package]
name = "command"
version = "0.1.0"
edition = "2021"

[lib]
path = "lib.rs"

[dependencies]
tauri = { workspace = true }
tauri-plugin-os = { workspace = true }

utils = { workspace = true }
account = { workspace = true }
install = { workspace = true }
task_manager = { workspace = true }